display_name: Procrastinator
package_name: Procrastinator

maintainer:
  name: Roman Avdeev
  email: RomanAAvdeev@proton.me

priority: optional

section: x11

installed_size: 15700

dependencies:
  - libsqlite3-0
  - libsqlite3-dev

icon: assets/img/logo-512.png

keywords:
  - Todo
  - Tasks
  - Task Manager

generic_name: An open source local to-do app

categories:
  - Office
  - Utility

startup_notify: true