name: Publish Release
on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - docs/
      - "README.md"
  push:
    # tags:
    #   - 'v*'
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"

env:
  FLUTTER_VERSION: "3.24.5"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' ./pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build_apk:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v3

      - name: Install Flutter actions dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq wget curl xz-utils git
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Install CMake ^3.14
        run: |
          sudo apt-get install -y build-essential libssl-dev pkg-config
          wget "https://cmake.org/files/v3.30/cmake-3.30.0-linux-x86_64.tar.gz"
          tar xvf cmake-3.30.0-linux-x86_64.tar.gz
          sudo mv cmake-3.30.0-linux-x86_64 /opt
          sudo ln -s --force /opt/cmake-3.30.0-linux-x86_64/bin/cmake /usr/local/bin/cmake

      - name: Install Java 17
        run: |
          sudo apt-get install openjdk-17-jdk openjdk-17-jre
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android Sdk
        run: sudo apt-get install android-sdk

      - name: Fix Flutter actions
        run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.24.5-x64

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-result
          path:
            ./build/app/outputs/flutter-apk/app-release.apk


  build_tar_x86_64:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v3

      - name: Install Flutter actions dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq wget curl xz-utils git
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Install CMake ^3.14
        run: |
          sudo apt-get install -y build-essential libssl-dev pkg-config
          wget "https://cmake.org/files/v3.30/cmake-3.30.0-linux-x86_64.tar.gz"
          tar xvf cmake-3.30.0-linux-x86_64.tar.gz
          sudo mv cmake-3.30.0-linux-x86_64 /opt
          sudo ln -s --force /opt/cmake-3.30.0-linux-x86_64/bin/cmake /usr/local/bin/cmake

      - name: Fix Flutter actions
        run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.24.5-x64

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev

      - name: Compile linux
        run: flutter build linux --release

      - name: Create tar.gz archive
        run: |
          cd ./build/linux/x64/release/bundle
          tar -czvf ../../../../../result.tar.gz *

      - name: Upload tar.gz archive
        uses: actions/upload-artifact@v4
        with:
          name: tar-gz-x86-64-result
          path: ./*.tar.gz

  build_deb_x86_64:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v3

      - name: Install Flutter actions dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq wget curl xz-utils git
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Install CMake ^3.14
        run: |
          sudo apt-get install -y build-essential libssl-dev pkg-config
          wget "https://cmake.org/files/v3.30/cmake-3.30.0-linux-x86_64.tar.gz"
          tar xvf cmake-3.30.0-linux-x86_64.tar.gz
          sudo mv cmake-3.30.0-linux-x86_64 /opt
          sudo ln -s --force /opt/cmake-3.30.0-linux-x86_64/bin/cmake /usr/local/bin/cmake

      - name: Fix Flutter actions
        run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.24.5-x64

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev

      - name: Enable dart_distributor
        run: dart pub global activate flutter_distributor

      - name: Update PATH
        run: echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> ~/.bashrc

      - name: Build deb package
        run: flutter_distributor package --platform linux --targets deb

      - name: Find deb file
        id: find_deb
        run: |
          {
            echo 'deb_path<<EOF'
            find ./dist -name "*.deb"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Check if deb file exists
        id: check_file
        run: |
          if [[ ! -f '${{ steps.find_deb.outputs.deb_path }}' ]]; then
            echo "File not found: ${{ steps.find_deb.outputs.deb_path }}"
            exit 1
          fi

      - name: Upload deb file
        uses: actions/upload-artifact@v4
        with:
          name: deb-x86-64-result
          path: ${{ steps.find_deb.outputs.deb_path }}

  build_appimage_x86_64:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v3

      - name: Install Flutter actions dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq wget curl xz-utils git
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Install CMake ^3.14
        run: |
          sudo apt-get install -y build-essential libssl-dev pkg-config
          wget "https://cmake.org/files/v3.30/cmake-3.30.0-linux-x86_64.tar.gz"
          tar xvf cmake-3.30.0-linux-x86_64.tar.gz
          sudo mv cmake-3.30.0-linux-x86_64 /opt
          sudo ln -s --force /opt/cmake-3.30.0-linux-x86_64/bin/cmake /usr/local/bin/cmake

      - name: Fix Flutter actions
        run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.24.5-x64

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2

      - name: Compile linux
        run: flutter build linux --release

      - name: Copy compiled linux files
        run: |
          mkdir AppDir
          cp -r ./build/linux/x64/release/bundle/* AppDir/

      - name: Copy Recipe to correct location
        run: cp ./scripts/AppImage/AppImageBuilder_x86_64.yml AppImageBuilder.yml

      - name: Copy logo to AppDir
        run: |
          mkdir -p AppDir/usr/share/icons/hicolor/32x32/apps
          cp ./assets/img/logo-32.png AppDir/usr/share/icons/hicolor/32x32/apps/procrastinator.png
          mkdir -p AppDir/usr/share/icons/hicolor/128x128/apps
          cp ./assets/img/logo-128.png AppDir/usr/share/icons/hicolor/128x128/apps/procrastinator.png
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          cp ./assets/img/logo-256.png AppDir/usr/share/icons/hicolor/256x256/apps/procrastinator.png
  
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@57c3bc6963f870ce3be103117de5b5e33ffbaeb6
        with:
          recipe: ./AppImageBuilder.yml

      - name: Upload AppImage file
        uses: actions/upload-artifact@v4
        with:
          name: appimage-x86-64-result
          path: ./*.AppImage

  build_windows_zip_x86_64:
     runs-on: windows-latest
     needs: build
     steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - uses: actions/checkout@v3

      - name: Fix Flutter actions
        run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.24.5-x64

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Compile for Windows
        run: flutter build windows --release

      - name: Zip compiled files
        working-directory: .
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath Procrastinator.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-x86-64-result
          path: ./Procrastinator.zip

  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - build_apk
      - build_tar_x86_64
      - build_deb_x86_64
      - build_appimage_x86_64
      - build_windows_zip_x86_64
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Release
        id: prepare_release
        run: |
          echo "RELEASE_VERSION=v${{ needs.build.outputs.version }}" >> $GITHUB_ENV
          echo "RELEASE_TAG=v${{ needs.build.outputs.version }}" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded artifacts
        run: ls -R ./artifacts

      - name: Rename artifacts
        run: |
          # Move the first matching APK file
          mv "$(find artifacts/apk-result -maxdepth 1 -name '*.apk' | head -n 1)" \
            "artifacts/Procrastinator-${{ needs.build.outputs.version }}-android-x64.apk"

          # Move the first matching TAR.GZ file
          mv "$(find artifacts/tar-gz-x86-64-result -maxdepth 1 -name '*.tar.gz' | head -n 1)" \
            "artifacts/Procrastinator-${{ needs.build.outputs.version }}-linux-x86-64.tar.gz"

          # Move the first matching DEB file
          mv "$(find artifacts/deb-x86-64-result -maxdepth 1 -name '*.deb' | head -n 1)" \
            "artifacts/Procrastinator-${{ needs.build.outputs.version }}-linux-x86-64.deb"

          # Move the first matching AppImage file
          mv "$(find artifacts/appimage-x86-64-result -maxdepth 1 -name '*.AppImage' | head -n 1)" \
            "artifacts/Procrastinator-${{ needs.build.outputs.version }}-linux-x86-64.AppImage"

          # Move the first matching ZIP file
          mv "$(find artifacts/windows-zip-x86-64-result -maxdepth 1 -name '*.zip' | head -n 1)" \
            "artifacts/Procrastinator-${{ needs.build.outputs.version }}-windows-x86-64.zip"


      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: v${{ needs.build.outputs.version }}
          files: |
            artifacts/Procrastinator-${{ needs.build.outputs.version }}-android-x64.apk
            artifacts/Procrastinator-${{ needs.build.outputs.version }}-linux-x86-64.tar.gz
            artifacts/Procrastinator-${{ needs.build.outputs.version }}-linux-x86-64.deb
            artifacts/Procrastinator-${{ needs.build.outputs.version }}-linux-x86-64.AppImage
            artifacts/Procrastinator-${{ needs.build.outputs.version }}-windows-x86-64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}